Revert "[IT-2327] Enable cloudtrail log encryption (#638)"
This reverts commit 52b8378e89c0df87b7dc432cfde33410b44bbcb8.
failed to deploy with error..
```
Invalid request provided: Insufficient permissions to access S3 bucket
sagebase-cloudtrail-231505186444 or KMS key arn:aws:kms:us-east-1:797640923903:key/3a8af29b-2dba-4261-bb03-a54972535a09.
(Service: CloudTrail, Status Code: 400, Request ID: bcc8d8ea-afbd-4fcc-b20b-89b99a8c2ca9)"
(RequestToken: 460cb4a9-8e38-c4bc-d1ed-331877266f35, HandlerErrorCode: InvalidRequest). (231505186444 = LogCentralAccount)
ERROR: Stack sagebase-cloudtrail in account 797640923903 (us-east-1) update failed. reason: Resource is
not in the state stackUpdateComplete (797640923903 = SageITAccount)
```