Revert "[IT-1766] Setup region restrictions (#624)"
This reverts commit 636ca8b78db2015a4e72830f56ffff4097fad585.

Revert due to AWS error..

```
ERROR: failed executing task: Attach Policy (RestrictUnsupportedRegionsSCP)
OC::ORG::OrganizationalUnit ScienceDevOU ConstraintViolationException: You
have attached the maximum number of policies to the specified target.
```