Fix update (#391)
The PR #390 to update AZ for SubnetD returned the following error.
```
ERROR: Resource SubnetD failed because CIDR Block must change if
Availability Zone is changed and VPC ID is not changed
```

Attempt to fix by bumping the SubnetD CIDR range. New setup
is..

* 10.100.1-99.x would be non public vpcs
* 10.100.100.x would be a public vpc internal range