Revert "[IT-4498] Setup redirect for apex domain (#1457)" (#1459)
This reverts commit aa3dd85f6229ab104f425a155a6c43e1f12f9ecd.

Revert due to error..
```
ERROR: Resource WebsiteBucket failed because Resource handler returned message:
"Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting
```