GH OIDC access to environments (#913)
Github requires the AWS OIDC role to have explicit access to github
environments as noted in
[GH issue 452](https://github.com/aws-actions/configure-aws-credentials/issues/452).
Otherwise the following error will occur when attempting to assume the OIDC role in
GH actions..

```
Error: Credentials could not be loaded, please check your action inputs: Could
not load credentials from any providers
```

This change enables GH OIDC access to GH environment.