Revert "[IT-2327] Enable cloudtrail log encryption (#636)"
This reverts commit 896beb17c8d15db3bbcb99c44eceec6444a15174.
Error from deployment..

```
DEBG: Setting build action on stack sagebase-cloudtrail for ***/us-east-1 to UpdateOrCreate - hash from state did not match. (*** = MasterAccount)
ERROR: Task CloudTrail validated failed. reason: Found multiple targets for reference to KmsKey. e.g: 420786776710/us-east-1, 649232250620/us-east-1,
449435941126/us-east-1, 383874245509/us-east-1, 325565585839/us-east-1, 153370007719/us-east-1, 745159704268/us-east-1, 797640923903/us-east-1,
231505186444/us-east-1, 140124849929/us-east-1, 867686887310/us-east-1, 804034162148/us-east-1, 465877038949/us-east-1, 237179673806/us-east-1,
464102568320/us-east-1, 055273631518/us-east-1, 563295687221/us-east-1, 841415736403/us-east-1, 975466401039/us-east-1, 216152803258/us-east-1,
634761300905/us-east-1, 611413694531/us-east-1, 386990716034/us-east-1, 888810830951/us-east-1, 728882028485/us-east-1, 035458030717/us-east-1,
631692904429/us-east-1, 607346494281/us-east-1, 681175625864/us-east-1, 254940560790/us-east-1, 743644221192/us-east-1, 087547153226/us-east-1,
526515999252/us-east-1, 638976327662/us-east-1 (420786776710 = BridgeDevAccount)
ERROR:
ERROR: ==========================
ERROR: Stopped performing task(s)
ERROR: Following tasks completed:
ERROR:  - Task CloudwatchTrailLog
ERROR: Following tasks failed:
ERROR:  - Task CloudTrail
ERROR: Following tasks were not executed:
ERROR:  - Task CloudTrailSumoLogicRole
ERROR: ==========================
ERROR:
ERROR: Task Cloudtrail validated failed. reason: Number of failed tasks 1 exceeded tolerance for failed tasks 0.
DEBG: Setting build action on stack sagebase-sso-bridgeprod-ios-developer for ***/us-east-1 to UpdateOrCreate - hash from state did not match. (*** = MasterAccount)

```