Point to schematic staging (Replace) (#1291)
Deployment of https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1290/files failed: https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/11919331993/job/33218806052

Due to:
```
 DEBG: Stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1) update starting... (797640923903 = SageITAccount)
ERROR: error updating CloudFormation stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1). 
Resource is not in the state stackUpdateComplete (797640923903 = SageITAccount)
ERROR: Resource DnsRecord failed because [Tried to create resource record set [name='schematic-staging.api.sagebionetworks.org.', type='CNAME'] but it already exists].
ERROR: Stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1) update failed. reason: Resource is not in the state stackUpdateComplete (797640923903 = SageITAccount)
Resource is not in the state stackUpdateComplete
```

I suspect because we're replacing a DNS record with a new stack. Instead, this change should point to the existing stack to update it's values with the new ALB. It should also destroy the "stage" stack DNS forwarding config.