fix from testing
We cannot setup guardduty on logcentral because that's where guardduty
data is saved to..

```
DEBG: Setting build action on stack sagebase-guardduty for 383874245509/us-east-1 to UpdateOrCreate - no existing target was found in state. (383874245509 = SynapseDWAccount)
DEBG: Setting build action on stack sagebase-guardduty for 325565585839/us-east-1 to None - hash matches stored target. (325565585839 = SynapseProdAccount)
DEBG: Stack sagebase-guardduty in account 231505186444 (us-east-1) update starting... (231505186444 = LogCentralAccount)
ERROR: error updating CloudFormation stack sagebase-guardduty in account 231505186444 (us-east-1).
Resource is not in the state stackCreateComplete (231505186444 = LogCentralAccount)
ERROR: Resource Detector failed because Resource creation cancelled.
ERROR: Resource GuardDutyBucket failed because sagebase-guardduty-finding already exists.
ERROR: Stack sagebase-guardduty in account 231505186444 (us-east-1) update failed. reason: Resource is not in the state stackCreateComplete (231505186444 = LogCentralAccount)
```