Update CFN deployer policy (#564)
We are getting an error when running `sam validate` using the
current CFN policy..

```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListPolicies
operation: User: arn:aws:sts::XXXXX4268:assumed-role/service-accounts-CfnDeployerServiceRole-1OJK3OAN1IAI/botocore-session-1661992869
is not authorized to perform: iam:ListPolicies on resource: policy path / because no
identity-based policy allows the iam:ListPolicies action
```

Update the CFN deployer policy to allow running the command
to validate sam templates